version: "3"

# NOTE: In order to run this docker-compose setup, please use ./run.sh

services:
  taco-bot:
    container_name: taco_bot
    build: .
    restart: on-failure
    environment:
      TACOBOT_MONGO_HOST: mongodb
      TACOBOT_TOKEN: ${TACOBOT_TOKEN}
    depends_on: 
      - mongodb

  mongodb:
    container_name: taco_bot_db
    image: mongo:3.4
